trigger: none

pool:
  vmImage: 'windows-latest'

name: 'Set dynamically from build task'

variables:
  solution: '**/Bluefragments.Utilities.Smtp.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  version.MajorMinor: '5.0'
  version.Revision: $[counter(variables['version.MajorMinor'], 0)]
  versionNumber: '$(version.MajorMinor).$(version.Revision)'

steps:
- task: PowerShell@2
  displayName: Set the name of the build (i.e. the Build.BuildNumber)
  inputs:
    targetType: 'inline'
    script: |
      [string] $buildName = "$(versionNumber)_$(Build.SourceBranchName)"
      Write-Host "Setting the name of the build to '$buildName'."
      Write-Host "##vso[build.updatebuildnumber]$buildName"

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VersionDotNetCoreAssemblies@2
  inputs:
    Path: '$(Build.SourcesDirectory)'
    Injectversion: true
    VersionNumber: '$(versionNumber)'
    OutputVersion: 'OutputedVersion'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'create nuget packages'
  inputs:
    command: 'pack'
    packagesToPack: '$(solution)'
    packDirectory: '$(Build.ArtifactStagingDirectory)/packages/nuget'
    nobuild: true
    versioningScheme: 'off'

- publish: '$(Build.ArtifactStagingDirectory)/packages/nuget'
  displayName: 'publish artifact: $(ArtifactNuGetName)'
  artifact: 'packages-nuget'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: NuGetCommand@2
  displayName: 'nuget push'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: 'push'
    nuGetFeedType: external
    publishFeedCredentials: 'nuget'